USE Shopstop;

DROP TABLE IF EXISTS attendance;
DROP TABLE IF EXISTS employee;
DROP TABLE IF EXISTS discount;
DROP TABLE IF EXISTS payment;
DROP TABLE IF EXISTS order_details;
DROP TABLE IF EXISTS `order`;
DROP TABLE IF EXISTS product;
DROP TABLE IF EXISTS supplier;
DROP TABLE IF EXISTS customer;
DROP TABLE IF EXISTS shop;
DROP TABLE IF EXISTS member;
